name = "cfblog"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "blog-db"
database_id = "fe0d4cc1-f071-4531-8ceb-c76605605518"

# R2 Storage binding
[[r2_buckets]]
binding = "MEDIA"
bucket_name = "cfblog-media"

# Workers AI binding
[ai]
binding = "AI"

# Environment variables
[vars]
JWT_SECRET = "your-jwt-secret-here-change-in-production"
